function [dz, dz_Grad] = DrummingArmDynamics(t, z, u)
% Load Model Parameters
SetParams

% Unpack State
QS = z(1,:);
QE = z(2,:);
QW = z(3,:);
QF = z(4,:);
QSP = z(5,:);
QEP = z(6,:);
QWP = z(7,:);
QFP = z(8,:);

% Unpack Controls
T_S  = u(1,:);
T_E = u(2,:);
T_W = u(3,:);
T_F = u(4,:);
F_D = u(5,:);

% Calculate Accelerations via Kane's EOM
CalculateEOM

% Output State Derivative dz
dz = [QSP; QEP; QWP; QFP; QSPP; QEPP; QWPP; QFPP];

% Calculate State Gradients - dxGrad = [nState, 1+n+m, nTime]
CalculateStateGradients;
dz_Grad = permute( cat(3, [DQSPDT; DQSPDQS; DQSPDQE; DQSPDQW; DQSPDQF; DQSPDQSP; DQSPDQEP; DQSPDQWP; DQSPDQFP; DQSPDT_S; DQSPDT_E; DQSPDT_W; DQSPDT_F; DQSPDF_D], [DQEPDT; DQEPDQS; DQEPDQE; DQEPDQW; DQEPDQF; DQEPDQSP; DQEPDQEP; DQEPDQWP; DQEPDQFP; DQEPDT_S; DQEPDT_E; DQEPDT_W; DQEPDT_F; DQEPDF_D], [DQWPDT; DQWPDQS; DQWPDQE; DQWPDQW; DQWPDQF; DQWPDQSP; DQWPDQEP; DQWPDQWP; DQWPDQFP; DQWPDT_S; DQWPDT_E; DQWPDT_W; DQWPDT_F; DQWPDF_D], [DQFPDT; DQFPDQS; DQFPDQE; DQFPDQW; DQFPDQF; DQFPDQSP; DQFPDQEP; DQFPDQWP; DQFPDQFP; DQFPDT_S; DQFPDT_E; DQFPDT_W; DQFPDT_F; DQFPDF_D], [DQSPPDT; DQSPPDQS; DQSPPDQE; DQSPPDQW; DQSPPDQF; DQSPPDQSP; DQSPPDQEP; DQSPPDQWP; DQSPPDQFP; DQSPPDT_S; DQSPPDT_E; DQSPPDT_W; DQSPPDT_F; DQSPPDF_D], [DQEPPDT; DQEPPDQS; DQEPPDQE; DQEPPDQW; DQEPPDQF; DQEPPDQSP; DQEPPDQEP; DQEPPDQWP; DQEPPDQFP; DQEPPDT_S; DQEPPDT_E; DQEPPDT_W; DQEPPDT_F; DQEPPDF_D], [DQWPPDT; DQWPPDQS; DQWPPDQE; DQWPPDQW; DQWPPDQF; DQWPPDQSP; DQWPPDQEP; DQWPPDQWP; DQWPPDQFP; DQWPPDT_S; DQWPPDT_E; DQWPPDT_W; DQWPPDT_F; DQWPPDF_D], [DQFPPDT; DQFPPDQS; DQFPPDQE; DQFPPDQW; DQFPPDQF; DQFPPDQSP; DQFPPDQEP; DQFPPDQWP; DQFPPDQFP; DQFPPDT_S; DQFPPDT_E; DQFPPDT_W; DQFPPDT_F; DQFPPDF_D]),  [3, 1, 2]);
end
